### ISSUE TITLE
Browser cookies

### ISSUE THREAD

**Issue by jackyfox** [kc5nra/obs-browser#16]
Hello! How can I save site authentication?
I have to sign in to [dotabuff.com](http://www.dotabuff.com/) with “Interract” on every OBS  restart

**Comment by OsirisNL** [comment]
The browser source now saves data like cookies and databases (IndexedDB).

**Comment by cach116** [comment]
Wow, this is absolutely huge!  I assume the cookie persists even if you restart OBS?

**Comment by OsirisNL** [comment]
Yes, it persists when you restart OBS.
