### ISSUE TITLE
Weird Scrolling Bars

### ISSUE THREAD

**Issue by Grandorg** [kc5nra/obs-browser#21]
Hi there i have a strange Bug/Problem with the current Version of the Browser Plugin for OBS Studio. I use it for the Rainwave wiget and lately i have issues when the Song Changes.

I get allways Scrollbard when the animation kicks in and vanishing soon it is complete. Here a Link to a Short video i recorded with the current OBS Version and the installed v1.20 of the Plugin.

https://vid.me/e/fhOS

Also the Bug with adding Filters to the Browser Plugin is still there and all of my Sources vanishing soon i use a Filter on it like Crop.

**Comment by OsirisNL** [comment]
Set overflow:hidden in the CSS.
