### ISSUE TITLE
Option to disable same origin policy

### ISSUE THREAD

**Issue by whs** [kc5nra/obs-browser#24]
It would be nice if we have an option to disable same origin policy similar to Chromium's `--disable-web-security`

**Comment by OsirisNL** [comment]
Try passing that argument to obs studio.

**Comment by clemibunge** [comment]
I tried this in OBS 16.1.1 and it didn't work...
I still get the same error `obs-browser: Uncaught (in promise) SecurityError: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.`
