### ISSUE TITLE
WebGL can't work with babylon.js on windows (1.24)

### ISSUE THREAD

**Issue by miaulightouch** [kc5nra/obs-browser#25]
launch obs with `--enable-gpu`, but sound only and show black screen.
32/64 bit has this issue.

babylon.js example: http://synergy-development.fr/babylonyzer/

**Comment by OsirisNL** [comment]
Try getting the latest zip and copying it over your obs-studio install folder.

**Comment by Lange** [comment]
I think that WebGL can work when `--disable-gpu-compositing` is active. In my experience, `--disable-gpu-compositing` is the only flag needed to achieve smooth performance. Perhaps completely disabling the GPU with `--disable-gpu` is unnecessary?

**Comment by OsirisNL** [comment]
Surprisingly doing everything on the cpu seems to achieve the best performance.

**Comment by miaulightouch** [comment]
sorry, it's typo.
I'm using latest version.(1.24)

**Comment by miaulightouch** [comment]
`--disable-gpu-compositing`, `--disable-gpu` work like obs without `--enable-gpu` and get no sound/video.

**Comment by Lange** [comment]
Yeah WebGL doesn't work with 1.24 or any previous version as far as I can tell. I think Jim said something a long time ago about there being missing DLLs?

**Comment by OsirisNL** [comment]
It should work with the current zip on the 1.24 release when using --enable-gpu

**Comment by miaulightouch** [comment]
It seems I can't use 32bit obs-studio on 64bit Windows, that would cause problem.

switch to 64bit, and it works.

**Comment by Lange** [comment]
Ah yes I'm seeing my problem, I had `--enable-gpu` but I also had `--disable-gpu-compositing`. Removing `--disable-gpu-compositing` allows WebGL to function.
