### ISSUE TITLE
Browser sometimes showing last frame briefly when reactivating source

### ISSUE THREAD

**Issue by trianglPixl** [kc5nra/obs-browser#26]
I've been working on a homemade scene overlay system to teach myself OBS and CSS/JS at the same time using the browser plugin. I have a simple HTML file that starts with the overlay elements offscreen that slide onto the screen when switching to its scene. I did this using the "Shutdown when not active" setting and it works well most of the time but will sometimes flash the last frame shown before the source disabled when disabling and reactivating the plugin. I tested this with my overlay by disabling it, changing some text and re-enabling it. When it flashes, it shows the text from before I made the changes.
I don't know much about how OBS plugins or CEF work, but it looks like the plugin is giving OBS an old frame before the browser can render a new one. [Here's a video.](http://gfycat.com/WarmComposedAfricanwilddog)
At the end of the video, I changed the text on the overlay and the flashed frame didn't have the new text.

I played with putting load on my computer and it happened more consistently when recording (which increased CPU usage to ~35-45% with a ton of videos on screen), so it might depend on how much load the computer is under.

Is this part of how CEF works? Is it possible to make the plugin wait until it has a fresh browser frame? Is this intended?

This happens when going between scenes and when manually toggling the source.
Windows 10 w/ Anniversary update (though I had the issue before the Anniversary update)
Intel i7-4702MQ kept at 2.5GHz because it's a poorly-cooled laptop in Summer (~3.2GHz boost, 2.2GHz base)
Tested in OBS Studio 0.15.4 and 0.15.2 with bundled browser plugin and 1.24 downloaded straight from Github

I'll do my best to provide more information if any is needed.

Also, I think "shutdown" is used as a noun and "shut down" is used as a verb. Just a minor gripe, though.

**Comment by CoDEmanX** [comment]
Why did you close the issue? Is it resolved, or by-design, or... ?
