### ISSUE TITLE
Request: js hook for scene changes

### ISSUE THREAD

**Issue by SReject** [kc5nra/obs-browser#35]
Along with `.onVisibilityChange()` I'd also like to see an `.onSceneChange(@visible as boolean, @scene as String)` hook that triggers when the scene changes passing along the scene name that was **SWITCHED TO**. This would reduce the need for differing BrowserSource sources that handle minor differences between various scenes.  

Currently, I use at least 4 differing BrowserSources where only one source is active dependent on the state of my stream: starting, actively streaming, be right back, and ending. All use a the same local source with a different URL parameter; `file://path/index.htm?scene=starting` for example.  

With the suggested js hook for scene changes, only a single global BrowserSource would be required thus reducing resources, load times, ease of use, etc.

**Comment by DDRBoxman** [comment]
Luckily, Jim just added the frontend API. I'll take a look into this sometime this week.

https://github.com/jp9000/obs-studio/commit/8836592d92284c454f2e2d00b512837d9c53cbe9#diff-54a36ef3dbdac6170da35286f00a0532R88

**Comment by SReject** [comment]
Instead of implementing each item of the interface as a callback function, would it be possible instead to implement them as an eventemitter that takes place on the browser window object? This would allow multiple context scripts to make use of the callback.

```javascript
window.addEventListener("obsstudio:visibilityChange", (evt) => {
    if (evt.data === true) { ... }
});

window.addEventListener("obsstudio:sceneChange", (evt) => {
    if (evt.data === "someScene") { ... }
});
```

This fits more inline with browser javascript progmas and allows for a tidier external interface.

**Comment by theunknownartisthour** [comment]
There appears to be an issue with changing scenes with hotkeys where the function doesn't fire. Fairly consistent, if you do happen to fix this, perhaps it'd be nice to add event for onSceneChangeWithHotkey()* and at the moment onSceneChangeWithoutHotkey(). Given the current behavior it seems possible.

**Comment by OsirisNL** [comment]
This works fine for me

**Comment by theunknownartisthour** [comment]
I've been chatting with people on mantis at the moment it seems to be windows 7 specific at the very least.

**Comment by OsirisNL** [comment]
Yes, you were talking to me on mantis. But I doubt that it's Windows 7 specific.
OBS Studio does not differentiate between scene changes doen by hotkeys or by using the mouse, it's all the same event.
