### ISSUE TITLE
Not work WebGL

### ISSUE THREAD

**Issue by Luchanso** [kc5nra/obs-browser#41]
I'm tried check WebGL via https://get.webgl.org/

So it disbled, and maybe you know how to activate webgl?
![image](https://cloud.githubusercontent.com/assets/2098777/19623624/22f3fbb2-98d8-11e6-8d86-a1f5b965b7c8.png)

I'm use OBS 0.16.2 (Windows 10 x64)

**Comment by Luchanso** [comment]
I'm found solution in https://github.com/kc5nra/obs-browser/issues/25 issue and fixed it via --enable-gpu. Now it work, thank you.

**Comment by mahmed0715** [comment]
Hi, I need help with webgl on streamlabs obs. its not supported it shows. how to use --enable-gpu?

**Comment by Luchanso** [comment]
@mahmed0715 try it via creating shortcut
![image](https://user-images.githubusercontent.com/2098777/64063662-c85abe80-cbff-11e9-8371-90ba526aa9eb.png)
![image](https://user-images.githubusercontent.com/2098777/64063673-ec1e0480-cbff-11e9-8187-a1178cbad3fa.png)

**Comment by WizardCM** [comment]
@mahmed0715 We do not provide support for Streamlabs' fork of OBS.

**Comment by mahmed0715** [comment]
btw Thanks
