### ISSUE TITLE
Draw different things on stream and in interact window?

### ISSUE THREAD

**Issue by Simran-B** [kc5nra/obs-browser#49]
I'm not sure how interacting with the browser source works internally (if it's drawn independently), but if it's possible, I would love to see a property `window.obsstudio.isInteractive` that could be used to let a web app draw different things in the window for interaction and the source as later seen on stream.

It could show additional (but perhaps confidential) info to the broadcaster, or simply to hide buttons to trigger actions on the page to the viewers.

BTW: Is there any chance that one could interact directly with the browser source preview instead of in a separate window? For certain applications it would probably be sufficient if the preview could receive left and right clicks to trigger actions (based on where you clicked, to simulate a button).

**Comment by CoDEmanX** [comment]
Can anyone clarify if something can be drawn in interactive mode, which will not be visible in the preview/stream?

**Comment by OsirisNL** [comment]
This is not possible, the interact window shows w/e the source shows.

**Comment by CoDEmanX** [comment]
Bummer! Any chance though to allow direct interaction without the popup window?

**Comment by OsirisNL** [comment]
No, OBS Studio would need to support that.

**Comment by kc5nra** [comment]
The way most people get around this is by using websockets to have two different 'views', and the one in obs is the rendered one while a control panel-esque view is what you would interact with outside of OBS.

**Comment by CoDEmanX** [comment]
That's what I guessed, having a web or a local service that renders differently (admin view in a browser tab, stream view in OBS). Was just curious.
