### ISSUE TITLE
Mouse cursor not shown on Output during interaction

### ISSUE THREAD

**Issue by bilogic** [kc5nra/obs-browser#63]
It will help alot if the mouse cursor can be shown while in interactive mode.

**Comment by OsirisNL** [comment]
The mouse cursor does show?

**Comment by bilogic** [comment]
Mouse cursor does not show on my output. Do I need to be using the beta version?

**Comment by bilogic** [comment]
I'm using the built-in browser source from OBS 17.0.2

**Comment by OsirisNL** [comment]
The mouse cursor doesn't show on the output, that's not what the interact mode is for.

**Comment by bilogic** [comment]
Sure, I understand, But this feature will be very useful for presentations. Hope you can consider. Thank you.

**Comment by dodgepong** [comment]
The browser source is intended to be a graphics layer on OBS for rendering HTML graphics. If all you want to do is show a browser window for the purposes of presentation, then use Display Capture to capture a browser window, and then you will be able to see the mouse.

**Comment by bilogic** [comment]
Yes, but Display Capture shows everything you have on your desktop and that infinite effect when OBS itself is shown giving an overall unprofessional feel. I understand how OBS and browser source is supposed to work. Just giving feedback on how I think it can be improved.

**Comment by dodgepong** [comment]
If you use Window Capture, you can capture the mouse cursor, and ONLY the window you select.

**Comment by bilogic** [comment]
Yes, tried that. Window Capture doesn't capture the drop down menus and child windows that some applications create.

**Comment by dodgepong** [comment]
Then use display capture and crop out the parts you don't want people to see.

The point is that what you are currently using the browser source for is not at all what it is intended for. Capturing the mouse is the opposite of what is desired with this plugin.
