### ISSUE TITLE
Action failed: Mouse Click , Move and Focus

### ISSUE THREAD

**Issue by shadow0162** [kc5nra/obs-browser#64]
Browser source is running well.But I can't use mouse to do action(like click & focus).I found some methods in  browser-manager-base.hpp : SendMouseClick , SendMouseMove. why mouse action is not work in view ?
obs studio 17.0.2
obs brower: 1.27

**Comment by OsirisNL** [comment]
Those only work with the interact mode.

**Comment by shadow0162** [comment]
how to start interact mode?

**Comment by OsirisNL** [comment]
You right-click the source and click Interact.

**Comment by shadow0162** [comment]
Ok，it's work. Thanks, you can closed the issue now.
