### ISSUE TITLE
Local Files don't reload when updated

### ISSUE THREAD

**Issue by kingargyle** [kc5nra/obs-browser#66]
I posted this bug on the OBS Studio project, but figure I'd post it here as well.

https://obsproject.com/mantis/view.php?id=808

The basic issue is that if a local HTML file is changed and updated, the file isn't automatically reloaded when the timestamp has been modified.   Manually having to go and refresh the file or switch scenes to get it to reload isn't fitting our use case.  We stream a lot of X-Wing Miniatures games, and are updating on screen information about ships and stats and storing them in HTML files.   It would be nice to have an option to force the files to reload if they have changed on disk, like the Text Source files do.

Also, I have tried using the META tags and javascript to force a refresh but the browser source seems to always load a cached version and only reloads if you force it to through the properties or through switching scenes.

A sample is attached to the OBS studio bug report that can be used.

**Comment by OsirisNL** [comment]
Use this to make it reload every 2 seconds.

function reload_page() {
	location.reload(true);
	setTimeout(reload_page,2000);
  }
  setTimeout(reload_page,2000);

**Comment by kingargyle** [comment]
> Use this to make it reload every 2 seconds.
> 
> function reload_page() {
> location.reload(true);
> setTimeout(reload_page,2000);
> }
> setTimeout(reload_page,2000);

Tried this, works fine in a Chrome browser, seems to have no affect in the obs-browser.  The content isn't refreshed.  Only switching away and then back to the scene does it refresh the contents.

**Comment by OsirisNL** [comment]
Then you are doing something wrong, i tested this in the browser source and it works.

**Comment by kingargyle** [comment]
I'm attaching the file, that I'm using and how I have this setup.  This works as expected in Chrome.
[player_sample.txt](https://github.com/kc5nra/obs-browser/files/752620/player_sample.txt)

**Comment by OsirisNL** [comment]
That's not the code I pasted.

**Comment by kingargyle** [comment]
@OsirisNL okay, I got yours to work.  Now as a learning experience for me, can you explain why yours works, and why using either.

<meta http-equiv="Refresh" content="5"/> (off the top of my head), and why the onLoad with the way I had done it, doesn't work right in OBS Browser but works in Chrome.   Really I'm trying to understand why one works and the other doesn't.
