### ISSUE TITLE
Add advance features like in CLRBrowser OBS Classic Plugin

### ISSUE THREAD

**Issue by Bigmacbook** [kc5nra/obs-browser#67]
It would be nice to set user agent and other settings that CLRBrowser has.

![](http://i.imgur.com/HH9Dalx.png)

**Comment by dodgepong** [comment]
That settings panel exists specifically because the Classic browser source is CLR-based. The browser source in OBS Studio uses CEF directly, so it's not like that panel can just be "added" back.

Are there other settings you want to be able to set other than User Agent, in particular?

**Comment by BarryCarlyon** [comment]
Yes, for me I'd like the Debugging stuff. So I can open the inspector up in chrome for the page open in CEF.

**Comment by OsirisNL** [comment]
For that you can just add --remote-debugging-port=9222 to the obs studio shortcut. Then just access http://localhost:9222/

**Comment by BarryCarlyon** [comment]
@OsirisNL outstanding, can we get that added to the documentation?

**Comment by macharborguy** [comment]
is it possible to enable the remote debugging from actual remote systems, and not just the "localhost" machine?  I have tried Binding OBS to the localhost's local network address, but am unable to access it from another PC on the network.

The remote PC/browser, basically, just sits there, as though the remote server is not sending any data, and just keeping the connection request alive.
