### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by DJaeger** [kc5nra/obs-browser#79]
How about translating the plugin?
It seems to be able to handly locale files also for plugins.

**Comment by jp9000** [comment]
Sorry about that -- we'll hopefully start adding translations for this plugin as well.  That's something we sort of forgot about.

**Comment by DJaeger** [comment]
That would be great.
I would do the german translation, as soon as it's implemented.

**Comment by OsirisNL** [comment]
The browser source can now be translated.
You can do that here: https://crowdin.com/project/obs-studio
