### ISSUE TITLE
Need 64 bit download for windows.

### ISSUE THREAD

**Issue by Gathilo1** [kc5nra/obs-browser#84]
Hey the link for windows is 32 bit according to 7zip. there isnt links by bits for windows. Even here in previous releases i tried downloading 1.28 and 1.27 and they were both 32 bit. so if anyone can get me a 64 bit windows link to download (dont care which version) that would be fantastic.

-Thanks
Gath

**Comment by Fenrirthviti** [comment]
Version 1.29 on the repo here has both 32 and 64 bit versions included. I think you're confused.

**Comment by Gathilo1** [comment]
What do you mean. Any ways can you just direct me to a link for a windows 64 bit download. The one on the page did not work. I downloaded it and it just didn't show up in the obs (yes I put it in the 64 but plugin folder) but 7 zip said it was 32 bit

**Comment by RytoEX** [comment]
Go to https://github.com/kc5nra/obs-browser/releases.  Download the latest release.  Extract the zip file's contents directly into your OBS Studio directory.  See the accompanying images below.  If you're still having problems after this, then you're going to have to be more specific about what steps you performed, what you expected to happen, and what actually happened.  I don't know what you mean by "7 zip said it was 32 bit" or what significance it would have in this case.

Download this:
![2017-07-13 01_06_23-releases kc5nra_obs-browser](https://user-images.githubusercontent.com/624931/28151509-0b0b6ef8-6769-11e7-96af-02a127239b7d.png)

---

Here's the 64bit folder inside the zip file:
![2017-07-13 01_09_24-obs-browser-1 29 zip_obs-plugins_](https://user-images.githubusercontent.com/624931/28151510-0b0bbb10-6769-11e7-8291-2f48c4eb4910.png)

---

Extract the entire zip file on top of your OBS Studio directory.
![2017-07-13 01_23_04-programs](https://user-images.githubusercontent.com/624931/28151663-eb14d55c-6769-11e7-88a0-da0f555ace01.png)

---

Here are the files extracted into obs-studio\obs-plugins\64bit:
![2017-07-13 01_13_03-obs-studio](https://user-images.githubusercontent.com/624931/28151508-0b0b2b50-6769-11e7-9843-f7738e107884.png)

---

Here's OBS Studio 19.0.3 64-bit on Windows running with the latest Browser Source (1.29):
![2017-07-13 01_16_56-obs 19 0 3 64bit windows - portable mode - profile_ untitled - scenes_ untitl](https://user-images.githubusercontent.com/624931/28151511-0b0f1bd4-6769-11e7-9dc6-72a3b58433eb.png)
