### ISSUE TITLE
where can i download cef_binary_3.2987.1581.gf8909fe?

### ISSUE THREAD

**Issue by yanllllk** [kc5nra/obs-browser#93]
this page: http://opensource.spotify.com/cefbuilds/index.html
can't find cef_binary_3.2987.1581.gf8909fe_x86 and cef_binary_3.2987.1581.gf8909fe_x64.

**Comment by DreadWingKnight** [comment]
Nothing to do with obs.

**Comment by OsirisNL** [comment]
Why do you need that one specifically? Current master works with branch 3112

**Comment by yanllllk** [comment]
thks,i will try 3112
