### ISSUE TITLE
The .class[attribute="value"]{ is not suported

### ISSUE THREAD

**Issue by Marcopole** [kc5nra/obs-browser#96]
_I tried on the last version of the plugin but the problem stills exists._

So, the problem is:
I made a CSS that replace the twitch emoticons for personal emoticons, but on OBS doesn't works.
I investigate why is not working and I found the problem! Its cause the plugin doesn't support the attribute selection.

If I put this code:
`.message-text img{
ACTION!
}`
And all emoticons changes perfectly 👍

But if I want to select each emoticon:
`.message-text img[alt="http://static-cdn.jtvnw.net/emoticons/v1/8/1.0"]{
ACTION!
}​`
The program doesn't understand it and nothing changes.

Can fix that on the next update? please... 🙏 

#  

Thanks for your time ^-^/

**Comment by OsirisNL** [comment]
The alt attribute for the img tags for the emoticons don't contain a link in the twitch chat.
Not sure on what page you are testing this, but attribute selectors definitely work.

**Comment by Marcopole** [comment]
On the code, the images have the atribute "alt" because i import that from restream.io (sorry, I didn't mention that 😅 )
And its strange... the CSS only fails when I use the plugin. Probably its a diferent bug that I thought.
Probably the code was printed in diferent way on OBS...
Well, I used the attribute "src" and now it works. 😄
Thanks for answer me so fast! You're awesome!

# 
I leave here [the css that I used at first](https://justpaste.it/1d5il) and [an example of using it outside of OBS](https://mcopernic.000webhostapp.com/chatbinario.html) in case you want to investigate something related and it helps.

Thanks for everything!
