### ISSUE TITLE
Browser Source is successfully built but not showing up, probably due to many necessary files not being copied.

### ISSUE THREAD

**Issue by vokama** [kc5nra/obs-browser#97]
**So I've built the CEF:** I've selected /MD compile option for all the targets and also removed cef_tests target (since it produced couple of "unresolved external symbol" errors).
**I've successfully built the plugin and obs-studio:** edited FindCEF.cmake so that it looks for the libcef_dll_wrapper in the right place, selected "BUILD_BROWSER" and deselected "USE_STATIC_CRT" parameters in cmake-gui.

But when I launch the app, Browser Source is not located in the list of sources. I think the problem has to do with necessary files missing: in "Release/obs-plugins/64bit" the only files that have to do with the browser source are _obs-browser.dll_ and _cef-bootstrap.exe_. All of the other *.dll, *.pak, *.bin files and "locales" folder are absent. How can I solve this problem?
I am building with Visual Studio 2013 x64 for Windows 10
OBS Studio version is 18.0.2
obs-browser version is 1.29

**Comment by OsirisNL** [comment]
Why are you using such an old version of OBS-studio and why aren't you using the latest master of the browser source?

**Comment by vokama** [comment]
> Why are you using such an old version of OBS-studio

I've been working on a fork for a while.
>why aren't you using the latest master of the browser source

Is it going to work correctly with the older OBS Studio version?

**Comment by vokama** [comment]
I don't think this problem has anything to do with OBS Studio version anyway, it seems like FindCEF is not working properly. Should I set some values except CEF_ROOT_DIR? It's weird that CMake doesn't produce "Could not find the CEF shared library" although there is no _libcef_ file in "Release/obs-plugins/64bit".

**Comment by OsirisNL** [comment]
The latest master has some fixes in the cmake stuff

**Comment by vokama** [comment]
@OsirisNL yes, [this commit](https://github.com/kc5nra/obs-browser/commit/c083f4f7c2a752d497c1a32b4079ae09beb51fd9) does indeed solve my problem. Sorry it took me so long to reply.
