### ISSUE TITLE
Get Streaming and Visibility state 

### ISSUE THREAD

**Issue by kseptorl** [kc5nra/obs-browser#98]
I'd like to have an option to retrieve Streaming and Visibility state.
Like the getCurrentScene:
window.obsstudio.getVisibilityState(function(data) {console.log(data);});
window.obsstudio.getStreamingState(function(data) {console.log(data);});

Is it possible to add such functionality?

**Comment by OsirisNL** [comment]
I did add a option to get the status of the various outputs for OBS, see the README.
Getting visibility state is a bit difficult, afaik it isn't possible to get the visibility state of a source in a scene.

**Comment by OsirisNL** [comment]
With the option i added you can already do what you want to get the streaming status.

**Comment by kseptorl** [comment]
Just notices the update for the streaming state. Looks great! Thanks a lot!
